In [8]:
import numpy as np
import pandas as pd
print('-------')
a=[1,2,3,4,5,6]
a_1=a[-3:]
a.reverse()
a_2=a
a.reverse()
a_3=[x**2 for x in a]
print(a_1,a_2,a_3)

print('--------')
b=[1,2,5,3,2,0]
b=np.array(b)
print(b)
print('mean of b:',b.mean())
b=b.reshape(2,3)
print(b)
print('mean each row:',b.mean(axis=1))
print('mean each column:',b.mean(axis=0))
print('third column of b:',b[:,2])
print("square of b:",b**2)


df=pd.read_csv("/starbucks.csv")
print('---------')
print("average calories:",df["Calories"].mean())
print('----------')
print("total number of categories:",len(df["Beverage_category"].unique()))
print('----------')
group=df.groupby("Beverage_category")
print(group["Calories"].mean())
print('----------')
print("beverage preparation which includes the most sugar:")
print(df[df["Sugars (g)"]==df["Sugars (g)"].max()]["Beverage_prep"])
print('---------')

def getint(name):
   return int(name.split('%')[0])
df2=df
df2["Calcium (% DV)"]=df["Calcium (% DV)"].apply(getint)
group_beverage=df2.groupby("Beverage")
print(group_beverage["Calcium (% DV)"].mean())

print('-------------')
a=df[df["Protein (g)"]==df["Protein (g)"].max()]
b=a[a["Total Fat (g)"]==a["Total Fat (g)"].min()]
print(b)







-------
[4, 5, 6] [1, 2, 3, 4, 5, 6] [1, 4, 9, 16, 25, 36]
--------
[1 2 5 3 2 0]
mean of b: 2.1666666666666665
[[1 2 5]
 [3 2 0]]
mean each row: [2.66666667 1.66666667]
mean each column: [2.  2.  2.5]
third column of b: [5 0]
square of b: [[ 1  4 25]
 [ 9  4  0]]
---------
average calories: 193.87190082644628
----------
total number of categories: 9
----------
Beverage_category
Classic Espresso Drinks              140.172414
Coffee                                 4.250000
Frappuccino® Blended Coffee          276.944444
Frappuccino® Blended Crème           233.076923
Frappuccino® Light Blended Coffee    162.500000
Shaken Iced Beverages                114.444444
Signature Espresso Drinks            250.000000
Smoothies                            282.222222
Tazo® Tea Drinks                     177.307692
Name: Calories, dtype: float64
----------
beverage preparation which includes the most sugar:
214    Venti Nonfat Milk
215           Whole Milk
Name: Beverage_prep, dtype: object
-------